VCDL-252 taxonomy changes
hashicorp/field-workshops-terraform pull request #421
Opened 2024-04-05 21:03 UTC by jennamwong

DO NOT MERGE!!!!!!
Taking out instances of Terraform Cloud and replacing with HCP Terraform.
Cannot merge until April 22, 2024.

2024-04-22 19:30 UTC, syedQuadri7 commented on instruqt-tracks/terraform-cloud-aws/track.yml
> +checksum: "16868046364266727064"
```suggestion

```

2024-04-22 19:30 UTC, syedQuadri7 commented on instruqt-tracks/terraform-cloud-aws/track.yml
> +id: jamndfnxfdi1
```suggestion
slug: hcp-terraform-aws
```

2024-04-22 19:33 UTC, syedQuadri7 commented on instruqt-tracks/terraform-cloud-aws/track.yml
> +owner: hashicorp-field-ops
```suggestion
owner: hashicorp
```

2024-04-22 19:37 UTC, syedQuadri7 commented on instruqt-tracks/terraform-cloud-gcp/track.yml
>  id: mjfywxvlky8d
```suggestion

```

2024-04-22 19:45 UTC, syedQuadri7 commented on instruqt-tracks/terraform-cloud-aws/track.yml
> +slug: hcp-terraform-aws
```suggestion
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

slug: hcp-terraform-aws
```

2024-04-22 19:45 UTC, syedQuadri7 requested changes
needs to add copyright

2024-04-22 19:50 UTC, syedQuadri7 commented on instruqt-tracks/terraform-cloud-aws/track.yml
need to add 
```
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
```

2024-04-23 16:05 UTC, jennamwong commented
Combined this PR into VCDL-251 branch

2024-04-23 16:05 UTC, closed without merging